In [1]:
import scipy.io
import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


def load_dataset(infile):
    mat = scipy.io.loadmat(infile)
    X = mat["csi"].T
    nsamples = mat["nsamples"].flatten()
    dim = mat["dim"].flatten()
    classnames = list(map(lambda s: s.strip().title(), mat["classnames"]))
    y = []
    for i in range(len(classnames)):
        y += [i] * nsamples[i]
    y = np.array(y)
    return X, y, nsamples, classnames, dim

In [2]:
X, y, _, classnames, _ = load_dataset("../dataset/rCSI-3.mat")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train an SVM classifier on the training data
clf = svm.SVC(kernel="rbf", decision_function_shape="ovo")
clf.fit(X_train, y_train)

# Predict the class labels for the test data
y_pred = clf.predict(X_test)

print(f"\n> Test Accuracy: {accuracy_score(y_test, y_pred)*100:.4f}%")
print("\n> Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print("\n> Classification Report :")
print(classification_report(y_test, y_pred, target_names=classnames))


> Test Accuracy: 97.0000%

> Confusion Matrix: 
[[100   0   0]
 [  2  94   4]
 [  1   2  97]]

> Classification Report :
              precision    recall  f1-score   support

       Empty       0.97      1.00      0.99       100
        Walk       0.98      0.94      0.96       100
        Jump       0.96      0.97      0.97       100

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



In [3]:
import warnings

warnings.filterwarnings("ignore")

X, y, _, classnames, _ = load_dataset("../dataset/rCSI-4.mat")

X = scaler.transform(X)
y_pred = clf.predict(X)

print(f"\n> Test Accuracy: {accuracy_score(y, y_pred)*100:.4f}%")
print("\n> Confusion Matrix: ")
print(confusion_matrix(y, y_pred))
print("\n> Classification Report :")
print(classification_report(y, y_pred, target_names=classnames))


> Test Accuracy: 35.2778%

> Confusion Matrix: 
[[  0   0 120]
 [  1  12 107]
 [  1   4 115]]

> Classification Report :
              precision    recall  f1-score   support

       Empty       0.00      0.00      0.00       120
        Walk       0.75      0.10      0.18       120
        Jump       0.34      0.96      0.50       120

    accuracy                           0.35       360
   macro avg       0.36      0.35      0.22       360
weighted avg       0.36      0.35      0.22       360

